import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={clsx('h-screen w-screen antialiased bg-grainy dark:bg-none bg-background', inter.className)}>{children}</body>
    </html>
  )
}
